### ISSUE TITLE
Feature request: 'Export as javascript' option

### ISSUE THREAD

**Issue by bitbutter** [inkle/inky#56] opened 2016-08-31 14:33 UTC
Currently if you 'export for web' from inky, the story is represented as an object assigned to a variable in a javascript file (eg. myStory.js). When using this 'for web' structure, and iterating on a story in inky, it'd be really convenient to be able to export a replacement for just this file, without exporting all the other parts that 'export for web' does.

What I'm doing right now is exporting for web each time, into a kind of throwaway directory, then copying over just the file i need into my 'live' project directory (in which I've made other changes specific to the way I'd like it presented) and deleting the rest. Feels messy.

**Comment by joethephish** [comment] 2016-08-31 16:21
Yup, definitely! Slightly differently worded, but this is actually a duplicate of https://github.com/inkle/inky/issues/28.

**Closed by joethephish** 2016-08-31 16:21 UTC
