### ISSUE TITLE
Inklecate process doesn't terminate after exiting Inky

### ISSUE THREAD

**Issue by davelowensohn** [inkle/inky#46] opened 2016-07-31 21:52 UTC
I'm getting a consistent issue that's causing my MacBook Pro (Yosemite) to drain the battery & run its fans at full blast by doing the following:

1. Start Inky (0.37.9)
2. Open my existing `story.ink` project
3. Make some changes
4. Save the file
5. Exit Inky

I ran `top` and it appears that `inklecate` is ramping up to 99%+ CPU usage instead of terminating properly, despite Inky having properly quit. (See attached screenshot.)

Can anyone else reproduce?
![inky-crazy-process](https://cloud.githubusercontent.com/assets/3239830/17279643/3cbee584-572e-11e6-9ffb-1700ab9dc5cb.png)

**Comment by joethephish** [comment] 2016-08-01 07:38
Hey! Yeah, I've had this a few times... It seems that it's [actually quite hard](https://www.exratione.com/2013/05/die-child-process-die/) to ensure that your child processes are killed off from node.js :-( Pretty frustrating.

I thought I'd manage to catch all instances of this happening, though it's possible that I've introduced a new bug at some point, so I'll take a look into it.

Thanks for the report!

**Comment by joethephish** [comment] 2016-08-01 07:49
Hrm, I'm not managing to reproduce this using the simple repro steps you describe. Are you managing to get it 100% using those steps? (When watching in Activity Monitor, the `inklecate_mac` entries usually hang around for 5-10 seconds before disappearing, and never show the 99% CPU issue.)

Not claiming it's not happening, but simply that the steps to repro may be a bit more subtle...

**Comment by davelowensohn** [comment] 2016-08-02 01:05
Thanks for the speedy followup. Here's a video of the whole process, no toffee required: http://take.ms/kOCsP

Very easy to kill by PID, but otherwise it sticks around until I restart. Mostly just wanted to report the issue in case anyone else is blowing through their laptop battery & wondering why.

Also, I should note that I'm a JS developer, so there's a very real chance I've `npm installed` something that makes this unique to my machine.

**Comment by wilg** [comment] 2016-08-02 02:45
I'm having this issue as well, I'll try to find a repro next time it happens.

**Comment by joethephish** [comment] 2016-08-02 07:27
The easiest way to clean it up is by using `pkill -kill inklecate_mac`.

I've considered calling this on the mac version before exiting but it's a massive hack, so I'd rather solve it properly!

**Comment by wilg** [comment] 2016-09-19 02:58
This now happens 100% of the time for me, _if I open a second window in Inky_.

Repro:

1. Open Inky (this will automatically open a blank document)
2. Create a new project with Command + N (you'll now have two `inklecate_mac` processes running)
3. Quit Inky with Command + Q
4. 💥 One `inklecate_mac` process exits, the other starts consuming CPU until it reaches 100%.

Also worth noting is I always open a second window in Inky because sometimes launching Inky by opening a .ink file doesn't open the file.

**Comment by joethephish** [comment] 2016-09-19 09:14
Argh, apologies, I'll get onto this as soon as I can... really wish I could nail this once and for all, but it's proving to be rather difficult :-/

**Comment by joethephish** [comment] 2016-09-20 13:06
But it turns out it was only "difficult" because I was being stupid. This (should HAHA) be fixed in 7a9f5bf5325eb8e93b6d99a97910ee6b0dc3edb3, and will be in the next release.

**Closed by joethephish** 2016-09-20 13:06 UTC
Labels: bug, help wanted, NEXT

**Comment by joethephish** [comment] 2016-09-20 16:21
Okay, would like to give the latest build a try? https://github.com/inkle/inky/releases/tag/0.5
