### ISSUE TITLE
Double scrollbars in player on Windows

### ISSUE THREAD

**Issue by joethephish** [inkle/inky#66] opened 2016-10-13 08:48 UTC
See this screenshot:

![image](https://cloud.githubusercontent.com/assets/858967/19342516/15be7464-912a-11e6-91df-c4ef561de1af.png)

[(Source)](https://twitter.com/le_re/status/786486426703503360)

**Comment by joethephish** [comment] 2016-10-14 08:27
It would be great if someone could take a look at fixing the CSS for this on Windows! Might just be a matter of setting the overflow to hidden on the x axis?

**Comment by isakgrozny** [comment] 2016-11-20 18:16
Dunno if this helps at all, but it's happening to me on MacOS (Yosemite) too.

**Comment by arashikou** [comment] 2017-01-11 21:08
I'm seeing it on my Ubuntu box as well. I'll take a stab at fixing it.

**Comment by bookofportals** [comment] 2017-03-26 06:09
@joethephish does this need to be closed? It looks like the above PR was intended to close it, but didn't due to the insertion of the word "issue" in "fixes issue #66".

**Comment by arashikou** [comment] 2017-03-27 03:18
Oops! My bad. I'm a GitHub newbie and didn't know about GitHub automatically closing issues if you [use the right words](https://help.github.com/articles/closing-issues-via-commit-messages/).

As far as I'm concerned, this is ready to be closed.

**Closed** 2017-03-27 08:50 UTC
Labels: bug, help wanted
