### ISSUE TITLE
Feature Request: adjustable font size

### ISSUE THREAD

**Issue by leegrey** [inkle/inky#51] opened 2016-08-17 06:23 UTC
It would be great to be able to make the editor text bigger and smaller with ctrl+plus / ctrl-minus, or with ctrl+scrollwheel, or even just a dropdown menu. The current size is a little hard on the eyes. I am currently hacking the font size using the Developer Tools to modify the css font-size value, but a built in feature would be perfect. 

This is a feature I would be willing to contribute when I have a chance... but right now I'm a bit too busy writing my Story for the IF competition. :) (Spellcheck is another feature I would be willing to contribute if I can find time.)

Thank you for releasing INK and INKY. I am very grateful for this amazing piece of IF technology. (And for the great games Inkle has made with it.)

**Comment by joethephish** [comment] 2016-08-17 09:35
Sounds good! Let us know if you start work on either of these two points :)

**Comment by joethephish** [comment] 2016-08-17 09:36
Oh, this is a duplicate of #25. Will close this one.

**Closed by joethephish** 2016-08-17 09:36 UTC
